title: Bromite - take back your browser
theme: jekyll-theme-tactile
url: https://www.bromite.org
author: csagan5
logo: /android-icon-192x192.png
image: /android-icon-192x192.png
latest_release: 67.0.3396.88
